### ISSUE TITLE
Acresentar Segurança ao requirements.txt

### ISSUE THREAD

**Issue by Delatorrea** [victormachadogp/vanilla-todo#15]
A instalação de um requirements.txt pode ter brecha de segurança, levando a instalar depêndencias maliciosas. Por isso o aconselhado é gerar e instalar as dependências com hashes, assim se for uma depêndencia maliciosa é póssível identificar e impedir a instalação.

**Comment by Delatorrea** [comment]
@jonathanmach se puder atribuir a mim essa tarefa, já estou finalizando. Obrigado!!

**Comment by cristiantcjti** [comment]
@Delatorrea  testamos as funcionalidades dessa issue e funcionou bem. 
Acreditamos que podem fazer o merge.

**Comment by cristiantcjti** [comment]
@Delatorrea  Conseguimos testar essa issue e funcionou bem.
