### ISSUE TITLE
Criar database models

### ISSUE THREAD

**Issue by jonathanmach** [victormachadogp/vanilla-todo#2]
[Para fins de pesquisa e consulta do time]
Caminho de tijolos amarelos, sobre como funciona as models no django:

https://tutorial.djangogirls.org/pt/django_models/

**Comment by cristiantcjti** [comment]
Hey @LivSith e @jonathanmach , peguei essa task para fazer. Porém, não sei se é meu dever ou não mover para o board 'in progress'. De qualquer forma tentei mover mas não esta liberado para mim mover.

**Comment by jonathanmach** [comment]
Essa é a ideia sim. Ao começar a trabalhar numa task, faz o assign dela para você e move para In Progress.
O @victormachadogp precisa liberar acesso para você

**Comment by cristiantcjti** [comment]
@danielfonseca  vc pode rodar o as models?

**Comment by R161511** [comment]
@cristiantcjti  → Testamos as models e rodou com sucesso! Glórias!! :)
