### ISSUE TITLE
Criar rotas

### ISSUE THREAD

**Issue by cristiantcjti** [victormachadogp/vanilla-todo#22]
/tasklists/

Explicação de URL's Django:
https://tutorial.djangogirls.org/pt/django_urls/

Melhores praticas:
https://desenvolvimentoparaweb.com/miscelanea/api-restful-melhores-praticas-parte-1/

**Comment by LivSith** [comment]
Boas praticas...
https://desenvolvimentoparaweb.com/miscelanea/api-restful-melhores-praticas-parte-1/
